version: '3.8'
services:
  server_registry:
    image: phongvanngo/dochero-server-registry
    ports:
     - 3000:8761
    container_name: server-registry
    
  account_service:
    image: phongvanngo/dochero-account-service
    ports:
     - 3002:8082
    container_name: dochero-account-service