version: '3.8'
services:
  server_registry:
    image: phongvanngo/dochero-server-registry:latest
    ports:
     - 3000:8761
    container_name: server-registry

  account_service:
    image: phongvanngo/dochero-account-service:test
    ports:
     - 3002:8082
    container_name: dochero-account-service
  
  api_gateway:
    image: phongvanngo/dochero-api-gateway:test
    ports:
     - 3001:8082
    container_name: dochero-api-gateway