# docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
     - ${JENKINS_PORT}:8080
    container_name: jenkins
    volumes:
     - ${JENKINS_DATA_PATH}/home/novapo/jenkins_compose/jenkins_configuration:/var/jenkins_home
     - ${JENKINS_DATA_PATH}/var/run/docker.sock:/var/run/docker.sock
     - ${JENKINS_DATA_PATH}/usr/local/bin/docker:/usr/local/bin/docker