version: '3.8'

services:
  postgres:
    container_name: np_postgres
    image: postgres
    environment:
      POSTGRES_USER: ksharkinc
      POSTGRES_PASSWORD: ksharkinc2022
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "54322:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: np_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-novapo@kshark.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-ksharkinc2022}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "54323:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: