version: '3'
services:
  mongo:
    container_name: np_mongodb
    image: mongo
    restart: always
    ports:
      - "54324:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ksharkinc
      MONGO_INITDB_ROOT_PASSWORD: ksharkinc2022