version: '3'
services:
  mongodb:
    restart: always
    container_name: np_mongo
    image: mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/db
    ports:
      - "54324:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ksharkinc
      - MONGO_INITDB_ROOT_PASSWORD=ksharkinc2022
      - MONGO_INITDB_DATABASE=mongo

