version: '3'
services:
  mongo:
    container_name: np_mongodb
    image: mongo
    restart: always
    port:
      - 270177:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ksharkinc
      MONGO_INITDB_ROOT_PASSWORD: ksharkinc2022